title: Ashi Zhou # your name (or website title) here
logo: "/images/family.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Kenyon College
  <br><br>
  Economics
  Philosophy
  <br><br>
  Data Mining + UIUX
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
